import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
import scipy.signal as sc
from scipy.sparse import csc_matrix, eye, diags
from scipy.sparse.linalg import spsolve 
from scipy.signal import medfilt
import warnings
warnings.filterwarnings('ignore')

def create_template(signal, rpeaks, final_rpeaks, sampling_rate = 500, len_template = 1200, position_rpeak = 400, show = False):  
    '''
    template = create_template(signal_processed, final_rpeaks, sampling_rate = 500, len_template = 1200, position_rpeak = 400, show = False)
    
    Creates a representative beat (template) for the input ECG.
    
    Inputs:
        signal (numpy array): single-lead ECG. 
        final_rpeaks (list): list containing the positions of the R peaks after removing beats from the non-dominant class.
        sampling_rate (float): the sampling frequency of the ECG. 
        len_template (int): desired length of the template in msec.
        position_rpeak (int): desired position of the R peak in msec. 
        show (boolean): if True displays the ECG signal with R peak positions and the resulting template
        
    Output:
        template (numpy array): template generated by averaging beats from the dominant class. 
    ''' 
    len_template_in_samples = int(convert_from_msec_to_samples(len_template, sampling_rate))
    position_rpeak_in_samples = int(convert_from_msec_to_samples(position_rpeak, sampling_rate))  
    
    corrected_signal, filtered_signal, baseline = baseline_correction(signal)
   
    dominant_beats = [ filtered_signal[k - position_rpeak_in_samples : k - position_rpeak_in_samples + len_template_in_samples] \
                       for k in final_rpeaks if (k - position_rpeak_in_samples > 0) \
                       and ( k - position_rpeak_in_samples + len_template_in_samples < len(filtered_signal) )]
    #for beat in dominant_beats:
    #    plt.plot(beat)
    #plt.show()
    
    template = list(_average(dominant_beats))  
    if show:
        #R peak detection
        time = [convert_from_samples_to_sec(i, sampling_rate, milli=False) for i in range(len(filtered_signal))]
        plt.figure(figsize = (16, 5))
        plt.title('Final R peaks (black), removed R peaks (red)')
        plt.plot(time, signal)
        plt.plot(time, np.array(corrected_signal))
        for peak in rpeaks: 
            if peak in final_rpeaks:
                plt.axvline(convert_from_samples_to_sec(peak, sampling_rate, milli=False), ls ='--', color='k')
            else:
                plt.axvline(convert_from_samples_to_sec(peak, sampling_rate, milli=False), ls ='--', color='tab:red') 
        plt.xlabel('Time (s)')
        plt.ylabel('Amplitude')
        plt.show() 
        
        #Template creation
        time = [convert_from_samples_to_sec(i, sampling_rate, milli=True) for i in range(len_template_in_samples)]
        plt.title('Average beat')
        plt.plot(time, template)
        plt.xlabel('Time (ms)')
        plt.ylabel('Amplitude')
        plt.show() 
    return template 

def get_final_rpeaks(signal, sampling_rate = 500, corr_threshold = 0.9):  
    '''
    final_rpeaks, rpeaks, signal_processed  = get_final_rpeaks(signal, sampling_rate = 500, corr_threshold = 0.9)
    
    R peaks for dominant class
    
    Inputs:
        signal (numpy array): single-lead ECG. 
        sampling_rate (float): the sampling frequency of the ECG.  
        corr_threshold (float): threshold of the correlation between QRS complexes (between 0 and 1). 
        
    Output:
        final_rpeaks (list): list containing the positions of the R peaks after removing beats from the non-dominant class.
        
        rpeaks (list): list containing the positions of the R peaks before removing beats from the non-dominant class.
    '''   
    corrected_signal, filtered_signal, baseline = baseline_correction(signal)
    
    rpeaks = find_rpeaks(np.array(corrected_signal), sampling_rate = sampling_rate)
    
    corr_scores, matrix_corr = get_corr_scores(corrected_signal, rpeaks, sampling_rate, corr_threshold)
    
    final_rpeaks = [peak for peak, corr in zip(rpeaks, corr_scores) if corr > corr_threshold] 
     
    return final_rpeaks, rpeaks, corr_scores, matrix_corr
 
def get_corr_scores(signal, rpeaks, sampling_rate, corr_threshold, window_size = 80) :   
    
    window_size_in_samples = sampling_rate*window_size/1000
    
    half_window_size = int(window_size_in_samples//2)
    
    list_nb_high_corr = [compute_number_high_corr(rpeak_ref, rpeaks, signal, sampling_rate, corr_threshold, window_size)['nb_high_corr'] \
                         for rpeak_ref in rpeaks]
    
    matrix_corr = [compute_number_high_corr(rpeak_ref, rpeaks, signal, sampling_rate, corr_threshold, window_size)['corr_scores'] \
                         for rpeak_ref in rpeaks]
    
    rpeak_most_high_corr = rpeaks[np.argmax(list_nb_high_corr)]
   
    corr_scores = matrix_corr[np.argmax(list_nb_high_corr)]
    
    return corr_scores, matrix_corr

def compute_number_high_corr(rpeak_ref, rpeaks, signal, sampling_rate, corr_threshold, window_size):
    '''
    nb_high_corr = compute_number_high_corr(rpeak_ref, rpeaks, signal, sampling_rate, corr_threshold, window_size)
    
    Compute number of high correlation scores between a reference complex and the other QRS compexes detected in the signal.
    
    Inputs:
        rpeak_ref (int): R peak position of the reference QRS complex.
        rpeaks (list): list containing the positions of the R peaks.
        signal (numpy array): single-lead ECG. 
        sampling_rate (float): the sampling frequency of the ECG.
        corr_threshold (float): threshold of the correlation between QRS complexes (between 0 and 1).
        window_size (float) : Window size in msec.
        
    Output:
        nb_high_corr (int): returns number of correlation scores above the correlation threshold 
    '''   
    
    window_size_in_samples = convert_from_msec_to_samples(window_size, sampling_rate)
    
    half_window_size = int(window_size_in_samples//2)
    
    corr_scores = [correlation(signal[rpeak-half_window_size:rpeak+half_window_size], \
                               signal[rpeak_ref-half_window_size:rpeak_ref+half_window_size]) for rpeak in rpeaks]
     
    nb_high_corr = len([corr for corr in corr_scores if corr > corr_threshold])
    summary = {}
    summary['nb_high_corr'] = nb_high_corr
    summary['corr_scores'] = corr_scores
    return summary

def find_rpeaks(signal, sampling_rate):
    '''
    rpeaks = find_rpeaks(signal, sampling_rate)
    
    Detects R peaks following a method proposed by Nabian et al. (2018) inspired by the Pan-Tompkins algorithm.  
    - Nabian, M., Yin, Y., Wormwood, J., Quigley, K. S., Barrett, L. F., &amp; Ostadabbas, S. (2018).
    An Open-Source Feature Extraction Tool for the Analysis of Peripheral Physiological Data.
    IEEE Journal of Translational Engineering in Health and Medicine, 6, 1-11.
    doi:10.1109/jtehm.2018.2878000 (code adapted from Neurokit library)
    
    Inputs:
        signal (numpy array): single-lead ECG. 
        sampling_rate (float): the sampling frequency of the ECG.
        
    Output:
        rpeaks (list): list containing the positions of the R peaks.
    '''
    window_size = int(0.4 * sampling_rate)  #for a window size of 400 msec
    
    abs_signal = np.abs(signal)
    
    medfilt_abs =  sc.medfilt(abs_signal , 21)  
    thresh_ampli = np.max(medfilt_abs[1 + window_size: len(signal)//2])/10
    
    rpeaks = []
    for i in range(1 + window_size, len(signal) - window_size):
        window = abs_signal[i - window_size : i + window_size]
        peak = np.argmax(window) 
        if peak == window_size + 1 and medfilt_abs[i - window_size : i + window_size][peak]>thresh_ampli: 
            rpeaks.append(i)  
    return rpeaks
    
def correlation(signal, ref): 
    '''
    corr = correlation(signal, ref)
    
    Computes correlation score between two signals.
    
    Inputs:
        signal (numpy array): signal to be analysed 
        ref (numpy array): reference signal
        
    Output:
        corr (float): correlation score between a given signal and a reference. 
    '''   
    cross_corr = cross_correlation(signal, ref)
    auto_corr_ref =  cross_correlation(ref, ref)
    auto_corr_signal =  cross_correlation(signal, signal)
    corr =  cross_corr/np.sqrt(auto_corr_ref*auto_corr_signal) 
    return corr

def cross_correlation(signal, ref):
    '''
    cross_corr = cross_correlation(signal, ref)
    
    Computes cross-correlation score between two signals.
    
    Inputs:
        signal (numpy array): signal to be analysed 
        ref (numpy array): reference signal
        
    Output:
        cross_corr (float): cross-correlation score between a given signal and a reference. 
    '''    
    mean_ref = np.mean(ref)
    cross_corr = sum([(val - mean_ref)*(ref-mean_ref) for val, ref in zip(signal, ref)])
    return cross_corr

def convert_from_msec_to_samples(duration, sampling_rate):
    return sampling_rate*duration//1000
            
def convert_from_samples_to_sec(nb_samples, sampling_rate, milli=False):
    if milli:
        return 1000*nb_samples/sampling_rate 
    else:
        return nb_samples/sampling_rate 

def _average(l):
    llen = len(l)
    def divide(x):   
        return x / llen 
    return map(divide, map(sum, zip(*l)))

def baseline_correction(signal): 
    filtered_signal = iir_notch_filter(signal) 
    baseline = medfilt(filtered_signal, 49)  
    #baseline = medfilt(baseline, 149)  
    corrected_signal = filtered_signal - baseline 
    return corrected_signal, filtered_signal, baseline

def iir_notch_filter(signal, sampling_rate=500, Q=30, fc=50): 
    b, a = sc.iirnotch(fc, Q, sampling_rate)
    filtered_signal = sc.lfilter(b, a, signal)
    return filtered_signal